### ISSUE TITLE
angular babelfish

### ISSUE THREAD

**Issue by Guria** [nodeca/babelfish#24]
This library worth to be wrap into angular module with directive, service, filter stuff.
Is there any wip in that way? Maybe someone from community started to develop such module for its own.

NB There is already some angular i18n modules but I wasn't able find one which fit me. At least it lacks of normal namespacing and such powerfull `stringify` method.

**Comment by puzrin** [comment]
Sorry, can't help with info about angular, i don't use it, and not familiar with available components.

**Comment by akzhan** [comment]
please take a look at https://www.npmjs.com/package/ng-babelfish
