### ISSUE TITLE
Question: Default fallback for country variant

### ISSUE THREAD

**Issue by btd** [nodeca/babelfish#26]
Hello.

I would like to ask question about using country variants:
```
var BabelFish = require('babelfish');
var i18n = new BabelFish('en-GB');
i18n.addPhrase('pt', 'test.a', 'Apelido')
i18n.addPhrase('pt-BR', 'test.a', 'Sobrenome')
i18n.addPhrase('pt', 'test.b', 'Título')
> i18n.t('pt', 'test.a')
'Apelido'
> i18n.t('pt-BR', 'test.a')
'Sobrenome'
> i18n.t('pt-BR', 'test.b')
'pt-BR: No translation for [test.b]'
```

Shouldn't last line fallback to 'pt' ? Or i should manually add every possible fallback with .setFallback?

Thanks.

**Comment by puzrin** [comment]
There are no such auto-fallbacks, because those are not acceptable in 100% of use cases. Use `.setFallback()` to define exact rules.

**Comment by btd** [comment]
Ok, thanks. Agree in general but FYI for pt-BR default is pt as defined there http://cldr.unicode.org/translation/default-content. Anyway i think i will better to add pt-PT and pt-BR instead of reinventing wheels.

**Comment by puzrin** [comment]
Usually people use base names only (ru)  or full names only (ru-RU) for all project. It's unordinary to have both translations and such fallback is not required at all.

Probably, you mean locale "autodetection", when browser sends "ru; ru-RU;". But this happens before babelfish call and usually normalize locale names length, according to your project needs. For example: https://github.com/nodeca/nodeca.core/blob/master/lib/autoload/hooks/server_chain/locale_set.js

**Comment by btd** [comment]
Yes, that is similar with what i want, will add preprocessing to set fallbacks.
